name: workflow-from-other-branches 
on:
  pull_request: 
    branches:
      - "! main"

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Run Hello World
        run: echo "Hello World!"  
